import { Platform } from "react-native";
import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get('window');
const getResponsive = (val: number) => Math.round(val * (width / 390));
export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: '#2B292999',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBox: {
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 20,
    maxHeight: '60%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  modalTitle: {
    fontWeight: '500',
    fontSize: 17,
    color: '#222E44',
    flex: 1,
  },
  closeBtn: {
    fontSize: 16,
    color: '#0088E7',
    marginLeft: 12,
    fontWeight: '600',
    right: 5,
  },
  input: {
    backgroundColor: '#F7F9FC',
    borderRadius: 9,
    height: 44,
    paddingHorizontal: 14,
    fontSize: 16,
    marginBottom: 10,
    color: '#222',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  inputIcon: {
    position: 'absolute',
    right: 12,
  },
  modalBtnRow: {
    flexDirection: 'row',
    marginTop: 22,
  },
  modalBtnClear: {
    flex: 1,
    backgroundColor: '#E6F1FB',
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: 'center',
    marginRight: 8,
  },
  modalBtnApply: {
    flex: 1,
    backgroundColor: '#1292E6',
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: 'center',
    marginLeft: 8,
  },
  modalBtnClearText: {
    color: '#1292E6',
    fontWeight: '500',
    fontSize: 15,
    top: 5,
  },
  modalBtnApplyText: {
    color: '#fff',
    fontWeight: '500',
    fontSize: 15,
  },
  header: {
    backgroundColor: '#007AFF',
    paddingTop: Platform.OS === 'ios' ? getResponsive(18) : getResponsive(55),
    paddingBottom: getResponsive(20),
    paddingHorizontal: 0,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    zIndex: 0,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: getResponsive(24),
  },
  headerTitle: {
    color: '#fff',
    fontSize: getResponsive(18),
    fontWeight: '600',
    textAlign: 'center',
    flex: 1,
  },
  searchBarFloatWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: -getResponsive(32),
    marginHorizontal: getResponsive(20),
    zIndex: 2,
    top: getResponsive(25),
  },
  searchBarFloat: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: getResponsive(8),
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    paddingHorizontal: getResponsive(10),
  },
  searchInput: {
    flex: 1,
    paddingHorizontal: 8,
    color: '#222',
    fontSize: getResponsive(17),
  },
  filterBtnFloat: {
    backgroundColor: '#fff',
    borderRadius: getResponsive(8),
    padding: getResponsive(9),
    marginLeft: getResponsive(8),
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: getResponsive(16),
    marginBottom: getResponsive(14),
    marginTop: getResponsive(8),
  },
  statCard: {
    backgroundColor: '#fff',
    borderRadius: getResponsive(14),
    padding: getResponsive(10),
    marginHorizontal: getResponsive(4),
    borderLeftWidth: getResponsive(6),
    borderRightWidth: 0,
    borderTopWidth: 0,
    borderBottomWidth: 0,
    elevation: 2,
    minHeight: getResponsive(64),
    justifyContent: 'center',
    alignItems: 'flex-start',
    shadowColor: '#0002',
    shadowOpacity: 0.06,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
  },
  statTitle: {
    fontSize: getResponsive(10),
    lineHeight: getResponsive(14),
  },
  statValue: {
    fontSize: getResponsive(12),
    fontWeight: '400',
    color: '#222',
  },
  boldNum: {
    fontWeight: 'bold',
    fontSize: getResponsive(13),
    color: '#222',
  },
  progressBox: {
    backgroundColor: '#fff',
    borderRadius: getResponsive(13),
    marginHorizontal: getResponsive(16),
    padding: getResponsive(18),
    marginBottom: getResponsive(16),
    elevation: 2,
    shadowColor: '#0002',
    shadowOpacity: 0.06,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getResponsive(8),
  },
  progressLabel: {
    width: getResponsive(78),
    fontSize: getResponsive(10),
    color: '#7A8194',
  },
  progressBarBg: {
    flex: 1,
    height: getResponsive(6),
    backgroundColor: '#E5E7EB',
    borderRadius: getResponsive(8),
    marginHorizontal: getResponsive(8),
    overflow: 'hidden',
  },
  progressBar: {
    height: getResponsive(6),
    borderRadius: getResponsive(8),
  },
  progressPercent: {
    width: getResponsive(50),
    textAlign: 'right',
    fontSize: getResponsive(10),
    color: '#222',
  },
  dateRangeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0088E714',
    borderRadius: getResponsive(11),
    marginHorizontal: getResponsive(16),
    padding: getResponsive(13),
    marginBottom: getResponsive(10),
    marginTop: getResponsive(4),
  },
  dateRangeText: {
    marginLeft: getResponsive(8),
    color: '#184B74',
    fontSize: getResponsive(11),
    fontWeight: '400',
  },
  taskCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: getResponsive(14),
    marginHorizontal: getResponsive(16),
    marginVertical: getResponsive(6),
    padding: getResponsive(14),
    elevation: 1,
    shadowColor: '#0001',
    shadowOpacity: 0.04,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },

  },
  taskIndicator: {
    width: getResponsive(6),
    height: getResponsive(56),
    borderRadius: getResponsive(6),
    marginRight: getResponsive(14),
  },
  taskTitle: {
    fontSize: getResponsive(14),
    fontWeight: '500',
    color: '#021639F5',
    marginBottom: getResponsive(3),
  },
  taskDates: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    // marginTop: getResponsive(2),
  },
  taskDate: {
    fontSize: getResponsive(10),
    color: '#7A8194',
    marginRight: getResponsive(22),
    fontWeight: '400',
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: getResponsive(60),
    backgroundColor: '#fff',
    borderTopLeftRadius: getResponsive(18),
    borderTopRightRadius: getResponsive(18),
    elevation: 10,
  },
    dropdownCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
    minWidth: 260,
    maxWidth: 340,
    alignSelf: 'flex-end',
  },
  activeSortBtn: {
    backgroundColor: '#E6F0FF',
    borderColor: '#007AFF',
    borderWidth: 2,
  },
    sortModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
    paddingHorizontal: 20,
  },
  sortModalTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#222',
  },
  sortModalCloseBtn: {
    marginLeft: 12,
  },
  sortModalCloseCircle: {
    width: 28,
    height: 28,
    borderRadius: 50,
    backgroundColor: '#0088E71A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sortModalBody: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 20,
  },
  sortModalField: {
    fontSize: 14,
    color: '#222',
    fontWeight: '400',
  },
  sortModalOrderBtns: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sortModalOrderBtn: {
    backgroundColor: '#F2F6FF',
    borderRadius: 20,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
});