
import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const CARD_RADIUS = 16;


const getResponsive = (val: number) => Math.round(val * (width / 390));


export const styles = StyleSheet.create({
    header: {
        backgroundColor: '#0088E7',
        paddingTop: Platform.OS === 'ios' ? getResponsive(18) : getResponsive(55),
        paddingBottom: getResponsive(14),
        paddingHorizontal: 0,
        alignItems: 'center',
        justifyContent: 'flex-start',
        zIndex: 0,
    },
    previewModal: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.98)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    previewImage: {
        width: '100%',
        height: '100%',
    },
    previewClose: {
        position: 'absolute',
        top: getResponsive(40),
        right: getResponsive(20),
        zIndex: 2,
        padding: getResponsive(8),
    },
    textFieldBox: {
        // light blue like the image
        backgroundColor: '#D9ECFF',
        borderRadius: getResponsive(10),
        padding: getResponsive(8),
        minHeight: getResponsive(50),
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#8CC7FF',
    },

    errorText: {
        color: '#F44336',
        fontSize: getResponsive(11),
        marginTop: getResponsive(4),
        marginLeft: getResponsive(4),
        fontWeight: '500',
        flexWrap: 'wrap',
    },
    textFieldInput: {
        color: '#021639',
        fontSize: getResponsive(12),
        fontWeight: '500',
        paddingVertical: getResponsive(4),
        paddingHorizontal: getResponsive(4),
        textAlignVertical: 'top',
    },
    footerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        paddingHorizontal: getResponsive(10),
        marginTop: getResponsive(10),
    },
    navBtn: {
        borderRadius: getResponsive(10),
        paddingVertical: getResponsive(10),
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: getResponsive(40),
        flexDirection: 'row',
    },
    btnPrimary: {
        backgroundColor: '#28B446',
    },
    submitBtn: {
        backgroundColor: '#28B446',
        borderRadius: getResponsive(10),
        paddingVertical: getResponsive(7),
        alignItems: 'center',
        justifyContent: 'center',
    },
    submitBtnText: {
        color: '#fff',
        fontSize: getResponsive(16),
        fontWeight: '600',
        letterSpacing: 0.8,
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        paddingHorizontal: getResponsive(24),
    },
    headerTitle: {
        color: '#fff',
        fontSize: getResponsive(20),
        fontWeight: '600',
        textAlign: 'center',
        flex: 1,
    },
    topCardFloatWrap: {
        alignItems: 'center',
        width: '100%',
        zIndex: 2,
        paddingHorizontal: getResponsive(16),
    },
    topCard: {
        backgroundColor: '#fff',
        borderRadius: getResponsive(14),
        padding: getResponsive(10),
        width: '100%',
        shadowColor: '#0002',
        shadowOpacity: 0.08,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
        marginBottom: getResponsive(8),
    },
    topCardTitle: {
        color: '#021639',
        fontWeight: '700',
        fontSize: getResponsive(16),
    },
    topCardSub: {
        color: '#02163980',
        fontWeight: '500',
        fontSize: getResponsive(12),
    },
    dot: {
        color: '#02163980',
        fontSize: getResponsive(18),
        marginHorizontal: 2,
        marginRight: getResponsive(8),
    },
    topCardDate: {
        fontSize: getResponsive(14),
        color: '#02163980',
        fontWeight: '500',
    },
    formCard: {
        backgroundColor: '#fff',
        borderRadius: CARD_RADIUS,
        marginHorizontal: getResponsive(12),
        shadowColor: '#0002',
        shadowOpacity: 0.08,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
        marginBottom: getResponsive(20),
    },
    formCardTitle: {
        color: '#19233C',
        fontSize: getResponsive(16),
        fontWeight: '600',
    },
    radioRow: {
        backgroundColor: '#F2F2F2',
        borderRadius: getResponsive(12),
        marginBottom: getResponsive(14),
        paddingHorizontal: getResponsive(10),
        flexDirection: 'row',
        flex: 1,
        justifyContent: 'space-between',
        alignItems: 'center',
        minHeight: getResponsive(80),

    },
    radioLabel: {
        color: '#19233C',
        fontSize: getResponsive(12),
        lineHeight: getResponsive(16),
        width: '40%',

    },
    radioChoiceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 2,
        width: '60%',
        justifyContent: 'flex-end',
    },
    radioOption: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: getResponsive(10),
        // marginRight: getResponsive(24),
    },
    radioOptionText: {
        color: '#19233C',
        fontSize: getResponsive(12),
        marginHorizontal: getResponsive(2),
    },
    mediaRow: {
        backgroundColor: '#F2F2F2',
        borderRadius: getResponsive(12),
        marginBottom: getResponsive(14),
        padding: getResponsive(16),
        flexDirection: 'row',
        // right: 200
        // backgroundColor: 'red',
    },
    multiImgBox: {
        backgroundColor: '#0088E733',
        borderRadius: getResponsive(6),
        marginTop: getResponsive(8),
        padding: getResponsive(8),
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        width: '50%',
        // minHeight: getResponsive(90),
    },
    multiImgThumbBox: {
        marginRight: getResponsive(8),
        marginBottom: getResponsive(4),
        position: 'relative',
    },
    multiImgThumb: {
        width: getResponsive(60),
        height: getResponsive(50),
        borderRadius: getResponsive(10),
        // backgroundColor: '#bbb',
        marginBottom: getResponsive(4),
    },
    attachmentThumb: {
        width: getResponsive(90),
        height: getResponsive(50),
        borderRadius: getResponsive(10),
        backgroundColor: '#E8F4FF',
        paddingHorizontal: getResponsive(6),
    },
    attachmentName: {
        color: '#021639',
        fontSize: getResponsive(9),
        fontWeight: '600',
        textAlign: 'center',
        paddingHorizontal: getResponsive(4),
    },
    multiImgRemove: {
        position: 'absolute',
        top: -7,
        right: -7,
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#1292E6',
        borderRadius: getResponsive(14),
        width: getResponsive(20),
        height: getResponsive(20),
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
        elevation: 2,
    },
    multiImgAddBtn: {
        marginLeft: getResponsive(10),
        marginRight: getResponsive(4),
    },
    // New attachment container styles
    attachmentContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#0088E733',
        borderRadius: getResponsive(6),
        padding: getResponsive(8),
        minHeight: getResponsive(60),
    },
    attachmentCameraBtn: {
        marginRight: getResponsive(8),
        padding: getResponsive(4),
    },
    attachmentScrollView: {
        flex: 1,
        maxHeight: getResponsive(60),
    },
    attachmentScrollContent: {
        alignItems: 'center',
        paddingRight: getResponsive(8),
    },
    attachmentThumbBox: {
        marginRight: getResponsive(8),
        position: 'relative',
    },
    attachmentRemove: {
        position: 'absolute',
        top: -7,
        right: -7,
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#1292E6',
        borderRadius: getResponsive(14),
        width: getResponsive(20),
        height: getResponsive(20),
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
        elevation: 2,
    },
    notesRow: {
        backgroundColor: '#F7F9FC',
        borderRadius: getResponsive(12),
        marginBottom: getResponsive(14),
        padding: getResponsive(16),
        flexDirection: 'row',
        minHeight: getResponsive(80),
    },
    notesBox: {
        backgroundColor: '#0088E733',
        borderRadius: getResponsive(6),
        marginTop: getResponsive(8),
        padding: getResponsive(8),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        flexWrap: 'wrap',
        width: '50%',
        marginLeft: 5,
    },
    notesText: {
        color: '#19233C',
        fontSize: getResponsive(10),
        fontWeight: '500',
    },
    signatureRow: {
        backgroundColor: '#F2F2F2',
        borderRadius: getResponsive(12),
        marginBottom: getResponsive(10),
        padding: getResponsive(16),
        flexDirection: 'row',
    },
    signatureBox: {
        borderRadius: getResponsive(10),
        marginTop: getResponsive(10),
        padding: getResponsive(5),
        minHeight: getResponsive(100),
        minWidth: getResponsive(180),
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    signatureImg: {
        width: getResponsive(180),
        height: getResponsive(100),
        borderRadius: getResponsive(6),
    },
    signatureOverlay: {
        position: 'absolute',
        top: 10,
        right: 12,
        backgroundColor: '#0088E7',
        padding: getResponsive(4),
        borderRadius: getResponsive(12),
    },
    submitBar: {
        backgroundColor: '#fff',
        paddingVertical: getResponsive(20),
        paddingHorizontal: getResponsive(12),
        borderTopWidth: 0,
        shadowColor: '#0002',
        shadowOpacity: 0.06,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: -2 },
        elevation: 6,
    },
    submitBtn: {
        backgroundColor: '#28B446',
        borderRadius: getResponsive(10),
        paddingVertical: getResponsive(7),
        alignItems: 'center',
        justifyContent: 'center',
    },
    submitBtnText: {
        color: '#fff',
        fontSize: getResponsive(16),
        fontWeight: '600',
        letterSpacing: 0.8,
    },
    lookupModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: getResponsive(20),
    },
    lookupModalContent: {
        backgroundColor: '#fff',
        borderRadius: getResponsive(16),
        width: '100%',
        maxHeight: '70%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    lookupModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: getResponsive(20),
        paddingVertical: getResponsive(16),
        borderBottomWidth: 1,
        borderBottomColor: '#ECECEC',
    },
    lookupModalTitle: {
        fontSize: getResponsive(16),
        fontWeight: '600',
        color: '#19233C',
        flex: 1,
    },
    lookupModalClose: {
        padding: getResponsive(4),
    },
    lookupModalCloseText: {
        fontSize: getResponsive(20),
        color: '#19233C',
        fontWeight: '600',
    },
    lookupModalScroll: {
        maxHeight: getResponsive(400),
    },
    lookupOption: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: getResponsive(20),
        paddingVertical: getResponsive(16),
        borderBottomWidth: 1,
        borderBottomColor: '#F2F2F2',
    },
    lookupOptionSelected: {
        backgroundColor: '#E3F2FD',
    },
    lookupOptionText: {
        fontSize: getResponsive(14),
        color: '#19233C',
        fontWeight: '500',
        flex: 1,
    },
    lookupOptionTextSelected: {
        color: '#0088E7',
        fontWeight: '600',
    },
    lookupOptionCheck: {
        fontSize: getResponsive(18),
        color: '#0088E7',
        fontWeight: 'bold',
        marginLeft: getResponsive(12),
    },
    // ...existing code...
    // Add below existing styles:
    signatureModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: getResponsive(20),
    },
    signatureModalContent: {
        backgroundColor: '#fff',
        borderRadius: getResponsive(16),
        width: '100%',
        maxWidth: 520,
        paddingVertical: getResponsive(12),
        paddingHorizontal: getResponsive(12),
    },
    signatureModalTitle: {
        fontSize: getResponsive(16),
        fontWeight: '600',
        color: '#19233C',
        textAlign: 'center',
        marginBottom: getResponsive(8),
    },
    signatureModalCanvas: {
        height: getResponsive(220),
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: getResponsive(10),
        overflow: 'hidden',
    },
    signatureModalBtns: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: getResponsive(12),
    },
    signatureBtn: {
        flex: 1,
        paddingVertical: getResponsive(10),
        borderRadius: getResponsive(8),
        alignItems: 'center',
        marginHorizontal: getResponsive(6),
    },
    qrScannerContainer: {
        flex: 1,
        backgroundColor: '#000',
    },
    qrScannerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: Platform.OS === 'ios' ? getResponsive(50) : getResponsive(20),
        paddingHorizontal: getResponsive(20),
        paddingBottom: getResponsive(10),
        backgroundColor: '#000',
    },
    qrScannerClose: {
        padding: getResponsive(8),
    },
    qrScannerCloseText: {
        color: '#fff',
        fontSize: getResponsive(20),
        fontWeight: '600',
    },
    qrScannerTitle: {
        color: '#fff',
        fontSize: getResponsive(18),
        fontWeight: '600',
        flex: 1,
        textAlign: 'center',
        marginRight: getResponsive(36), // To center the title (accounting for close button)
    },
    qrScannerCamera: {
        flex: 1,
    },
    qrValidatorInfo: {
        backgroundColor: '#1a1a1a',
        paddingHorizontal: getResponsive(20),
        paddingVertical: getResponsive(12),
        borderBottomWidth: 1,
        borderBottomColor: '#333',
    },
    qrValidatorInfoText: {
        color: '#fff',
        fontSize: getResponsive(14),
        textAlign: 'center',
    },
    qrValidatorExpectedValue: {
        color: '#4CAF50',
        fontWeight: 'bold',
    },
    // Attachment Modal Styles
    attachmentModalContainer: {
        flex: 1,
        // height: '80%',
        backgroundColor: '#fff',
        // marginTop: 'auto',
        borderTopLeftRadius: getResponsive(20),
        borderTopRightRadius: getResponsive(20),
    },
    attachmentModalHeader: {
        flexDirection: 'row-reverse',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: getResponsive(20),
        paddingVertical: getResponsive(15),
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    attachmentModalClose: {
        width: getResponsive(30),
        height: getResponsive(30),
        borderRadius: getResponsive(15),
        backgroundColor: '#f5f5f5',
        justifyContent: 'center',
        alignItems: 'center',
    },
    attachmentModalCloseText: {
        fontSize: getResponsive(16),
        color: '#666',
        fontWeight: 'bold',
    },
    attachmentModalTitle: {
        fontSize: getResponsive(18),
        fontWeight: 'bold',
        color: '#19233C',
    },
    attachmentModalContent: {
        flex: 1,
        padding: getResponsive(20),
    },
    attachmentDropZone: {
        borderWidth: 2,
        borderColor: '#e0e0e0',
        borderStyle: 'dashed',
        borderRadius: getResponsive(12),
        padding: getResponsive(40),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fafafa',
        marginBottom: getResponsive(20),
    },
    attachmentDropIcon: {
        fontSize: getResponsive(48),
        marginBottom: getResponsive(16),
    },
    attachmentBrowseBtn: {
        backgroundColor: '#0088E7',
        paddingHorizontal: getResponsive(24),
        paddingVertical: getResponsive(12),
        borderRadius: getResponsive(8),
        marginBottom: getResponsive(8),
    },
    attachmentBrowseBtnText: {
        color: '#fff',
        fontSize: getResponsive(16),
        fontWeight: '600',
    },
    attachmentDropText: {
        fontSize: getResponsive(14),
        color: '#666',
        textAlign: 'center',
    },
    attachmentFileList: {
        marginTop: getResponsive(10),
    },
    attachmentFileItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: getResponsive(12),
        paddingHorizontal: getResponsive(16),
        backgroundColor: '#f8f9fa',
        borderRadius: getResponsive(8),
        marginBottom: getResponsive(8),
    },
    attachmentFileInfo: {
        flex: 1,
        marginRight: getResponsive(12),
    },
    attachmentFileName: {
        fontSize: getResponsive(14),
        color: '#19233C',
        fontWeight: '500',
    },
    attachmentFileSize: {
        fontSize: getResponsive(12),
        color: '#666',
        marginTop: getResponsive(2),
    },
    attachmentFileDelete: {
        width: getResponsive(24),
        height: getResponsive(24),
        borderRadius: getResponsive(12),
        backgroundColor: '#ff4757',
        justifyContent: 'center',
        alignItems: 'center',
    },
    attachmentFileDeleteText: {
        color: '#fff',
        fontSize: getResponsive(12),
        fontWeight: 'bold',
    },
    attachmentUploading: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: getResponsive(16),
    },
    attachmentUploadingText: {
        marginLeft: getResponsive(8),
        fontSize: getResponsive(14),
        color: '#0088E7',
    },
    attachmentModalFooter: {
        padding: getResponsive(20),
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
    },
    attachmentUploadBtn: {
        backgroundColor: '#0088E7',
        paddingVertical: getResponsive(16),
        borderRadius: getResponsive(8),
        alignItems: 'center',
    },
    attachmentUploadBtnText: {
        color: '#fff',
        fontSize: getResponsive(16),
        fontWeight: '600',
    },
    // New styles for QR Code and Barcode controls
    qrCodeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        paddingHorizontal: getResponsive(12),
        paddingVertical: getResponsive(8),
        borderRadius: getResponsive(8),
        flex: 1,
        marginRight: getResponsive(8),
    },
    qrCodeIconContainer: {
        width: getResponsive(32),
        height: getResponsive(32),
        borderRadius: getResponsive(16),
        // backgroundColor: '#0088E7',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: getResponsive(8),
    },
    qrCodeText: {
        fontSize: getResponsive(14),
        color: '#021639',
        fontWeight: '500',
    },
    barcodeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        paddingHorizontal: getResponsive(12),
        paddingVertical: getResponsive(8),
        borderRadius: getResponsive(8),
        flex: 1,
        marginRight: getResponsive(8),
    },
    // Used in validators to keep icon close to the Scan button
    validatorIconRow: {
        flex: 0,
        paddingLeft: getResponsive(8),
        marginRight: getResponsive(8),
    },
    barcodeIconContainer: {
        width: getResponsive(32),
        height: getResponsive(32),
        borderRadius: getResponsive(16),
        // backgroundColor: '#0088E7',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: getResponsive(8),
    },
    barcodeText: {
        fontSize: getResponsive(14),
        color: '#021639',
        fontWeight: '500',
    },
    scanButton: {
        backgroundColor: '#0088E7',
        paddingHorizontal: getResponsive(16),
        paddingVertical: getResponsive(8),
        borderRadius: getResponsive(6),
        justifyContent: 'center',
        alignItems: 'center',
        minWidth: getResponsive(60),
    },
    scanButtonText: {
        color: '#fff',
        fontSize: getResponsive(14),
        fontWeight: '600',
    },
    // New styles for input field and validation message
    inputFieldContainer: {
        flex: 1,
        marginRight: getResponsive(8),
    },
    inputField: {
        backgroundColor: '#F5F5F5',
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: getResponsive(8),
        paddingHorizontal: getResponsive(12),
        paddingVertical: getResponsive(8),
        fontSize: getResponsive(14),
        color: '#021639',
    },
    validationMessageContainer: {
        flex: 1,
        marginRight: getResponsive(8),
        justifyContent: 'center',
    },
    validationMessage: {
        fontSize: getResponsive(14),
        fontWeight: '600',
        textAlign: 'center',
    },
    // Date control styles
    dateInputContainer: {
        flex: 1,
    },
    dateInputField: {
        backgroundColor: '#F5F5F5',
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: getResponsive(8),
        flex: 1,
        minWidth: getResponsive(180),
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: getResponsive(4),
        paddingVertical: getResponsive(12),
        marginVertical: getResponsive(12),
    },
    dateInputText: {
        flex: 1,
        fontSize: getResponsive(14),
        paddingHorizontal: getResponsive(12),
        color: '#021639',
    },
    dateInputSeparator: {
        width: 1,
        height: getResponsive(20),
        backgroundColor: '#E0E0E0',
        marginHorizontal: getResponsive(8),
    },
    calendarIconContainer: {
        width: getResponsive(32),
        height: getResponsive(32),
        backgroundColor: '#F5F5F5',
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: getResponsive(6),
        justifyContent: 'center',
        alignItems: 'center',
    },
});